server:
  port: 8080

spring:
  application:
    name: conecta-brasil-backend

# Configurações do Stellar/Soroban - #todo: ajustar para variaveis de ambiente
stellar:
  network-passphrase: "Test SDF Network ; September 2015"   # TESTNET
  horizon-url: "https://horizon-testnet.stellar.org"
  soroban-rpc-url: "https://soroban-testnet.stellar.org"    # ou http://localhost:8000/soroban/rpc no localnet
  contract-address: "CBHMSNEPOIX3FQHIPIOSAGXE54GIYHHH5ZTT3IQGSJ6FF2NHNC5RRJJU"
  token-asset-address: "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC"


# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger
